image: gradle:7.6-jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test

test:
  stage: test
  script:
    - gradle test --stacktrace
